FROM ruby:3.2
WORKDIR /app
RUN apt-get update -qq && apt-get install -y build-essential libsqlite3-dev nodejs
COPY Gemfile* ./
RUN bundle install
COPY . .
CMD ["bash", "-c", "bin/rails db:migrate && rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0"]
